//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingDetail
    {
       
        public int Id { get; set; }

        [Display(Name = "Booking Number")]
        public int BookingNumber { get; set; }

        [Display(Name = "Client Name")]
        public string NameOfClient { get; set; }

        public string Nationality { get; set; }
        public string Detonation { get; set; }

        [Display(Name = "Hotel Name")]
        public string HotelName { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime CheckIn { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime CheckOut { get; set; }

        [Display(Name = "Total Nights")]
        public decimal TotalNights { get; set; }

        [Display(Name = "Net Price")]
        public decimal NetPrice { get; set; }

        [Display(Name = "Selling Rate")]
        public decimal SellingRate { get; set; }
        public decimal Markup { get; set; }

        [Display(Name = "Number Of Pax")]
        public string NumberOfPax { get; set; }

        public string Contact { get; set; }
        public string Remarks { get; set; }

        [Display(Name = "Special Ocassion")]
        public string SpecialOcassion { get; set; }

        [Display(Name = "Supplier Name")]
        public string Supplier { get; set; }

        [Display(Name = "Total Number Of Bookings")]
        public decimal TotalNumberOfBookings { get; set; }

        [Display(Name = "Total Selling")]
        public decimal TotalSelling { get; set; }

        [Display(Name = "Total Number Of Nights")]
        public decimal TotalNumberOfNights { get; set; }

        [Display(Name = "Total Net Rate")]
        public decimal TotalNetRate { get; set; }
    }
}
